apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: stripe-properties
  namespace: prod
spec:
  encryptedData:
    STRIPE_API_KEY: AgCkaeSdzoosoyr080LyUBObbVGSlefJbHcSt0VDJIGkxwmibuHTiDID7teMowHmdMHWa3Z+6gbb+xNYzegYt6/RJa4XoEgFvqvrh4y3NnohNUGviOipF0xYrahkv7f/z5VOkEn9smGhHsgmWiqxxWF6IaB7dQ6e8vew82D3khU9LYFTObI1EPAEOz8hp0zvrMakb85e1VSrVfQkfu8zv5hZQJYGZnLwlpILCHmp7ytuFnNy+bl60rUtWWw0fzg0gUiI77jV4U9coF14NnPh4tRXSrDPc2EsGS47qK/RAKiQJh9gjiDcF152LSAaAp+nPL2bwwe6/PclUUons4A0iHYZvo++nX/NCQAw6VClA6Uhnho0KVY6e/URW/4LOB277hXgHqKE+yT79iDMvN31oEmi8A9Mf4JJD9zLxxQRNuLo7uvmDgDOUx17KgCqO+2/awM70/6IOfp17BB0JMPXwQtEDkPTeaFWULnboiLfBu7/PYukEe9o5nYZYKnFo+qX+19Rsbxm27J3QxCvyWwQ/+Skcu8mprEYKJI6GKR4/OjLYDA+89OfDtiRrFGpA5MlJaTGg9D/538KJyPbcbAFezCQHaU6M5PGuDlg5O4bsd1SdFHB4oGaHXpeQrk9XYgStu4ZASJf/js/xjfASnsCB22Sqtgzqii9pUjwtWAx67uQK3UN2SJ8MbU1gZfzdqLsZlplV9/c2L96RDsZCsn8nfH7uXVvoeYEn2GXAVkw6GIQW0u6MWUb48o5EkXIDlEhH3XbMlCveAxb2uPEzYVNLZ2rVwpzeGWoj5qfOwJzzaLjwYasG4gsitkmaOovuncEiAMRat/0o9DI/YSSYw==
  template:
    metadata:
      creationTimestamp: null
      name: stripe-properties
      namespace: prod

