# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

# list of Resource Config to be Applied
resources:
- deployment.yaml

# namespace to deploy all Resources to
namespace: dev

# labels added to all Resources
commonLabels:
  deployment_env: local_dev


configMapGenerator:
- name: frontend-properties
  envs: 
  - frontend.properties
- name: backend-properties
  envs: 
  - backend.properties
  behavior: merge


secretGenerator:
- name: google-service-account
  files: 
    - google-SA-secret.txt
  type: Opaque
- name: jwt-secret
  files: 
    - jwt-secret
  type: Opaque
- name: django-secret
  files: 
    - django-secret
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
