# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

# list of Resource Config to be Applied
resources:
- deployment.yaml

# namespace to deploy all Resources to
namespace: dev

# labels added to all Resources
commonLabels:
  deployment_env: local_dev


configMapGenerator:
- name: backend-properties
  behavior: merge
  envs: 
  - backend.properties
- name: controller-properties
  behavior: merge
  envs:
  - controller.properties


secretGenerator:
- name: google-sa-secret
  files: 
    - google-SA-secret.txt
  type: Opaque
- name: jwt-secret
  files: 
    - jwt-secret
  type: Opaque
- name: django-secret
  files: 
    - django-secret
  type: Opaque
- name: database-properties
  envs: 
  - database.properties
- name: email-properties
  envs: 
  - email.properties
- name: stripe-properties
  envs:
  - stripe.properties

generatorOptions:
  disableNameSuffixHash: true
