FROM node:15.12.0-alpine3.10

RUN apk add git

WORKDIR /app

COPY package.json /app/package.json
# COPY package-lock.json /app/package-lock.json
RUN npm install

COPY . /app

#https://github.com/facebook/create-react-app/issues/8688#issuecomment-642309787
ENV CI=true

# These need to be backed in at build time
# https://create-react-app.dev/docs/adding-custom-environment-variables/
ENV REACT_APP_BACKEND_SERVER_PORT=8000
ENV REACT_APP_BACKEND_SERVER_ADDRESS=localhost
ENV REACT_APP_BACKEND_SERVER_PROTOCOL=http

ENV REACT_APP_QUERY_SERVER_PORT=8080
ENV REACT_APP_QUERY_SERVER_ADDRESS=localhost
ENV REACT_APP_QUERY_SERVER_PROTOCOL=http

ENV REACT_APP_REPORTER_SERVER_PORT=9090
ENV REACT_APP_REPORTER_SERVER_ADDRESS=localhost
ENV REACT_APP_REPORTER_SERVER_PROTOCOL=http

ENV REACT_APP_STRIPE_PUBLIC_KEY="pk_test_51IWi1NDCzbZohuMOijpMRzx7twohXqP9yTv2HIJMcUxLrYaPJEtM50aepVXa5qRP8UaSIhPzKsFMNACQsdUNfMYb00h7BfDUwz"
ENV REACT_APP_IN_DEV=1

CMD npm start
