FROM node:alpine

WORKDIR /app

COPY package.json /app/package.json
RUN npm install

COPY . /app

#https://github.com/facebook/create-react-app/issues/8688#issuecomment-642309787
ENV CI=true

# These need to be backed in at build time
# https://create-react-app.dev/docs/adding-custom-environment-variables/
ENV REACT_APP_BACKEND_SERVER_PORT=8000
ENV REACT_APP_BACKEND_SERVER_ADDRESS=localhost
ENV REACT_APP_BACKEND_SERVER_PROTOCOL=http

ENV REACT_APP_QUERY_SERVER_PORT=8080
ENV REACT_APP_QUERY_SERVER_ADDRESS=localhost
ENV REACT_APP_QUERY_SERVER_PROTOCOL=http

ENV REACT_APP_REPORTER_SERVER_PORT=9090
ENV REACT_APP_REPORTER_SERVER_ADDRESS=localhost
ENV REACT_APP_REPORTER_SERVER_PROTOCOL=http


CMD npm start
