apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: easytensor
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: easytensor/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer: ["**/*"]
    - image: easytensor/backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        infer: ["**/*"]
    - image: easytensor/migrations
      context: backend
      docker:
        dockerfile: Dockerfile.migrations
      sync:
        infer: ["**/*"]
    - image: easytensor/controller
      context: controller
      docker:
        dockerfile: Dockerfile
    - image: easytensor/reporter
      context: reporter
      docker:
        dockerfile: Dockerfile
      sync:
        infer: ["**/*"]
    - image: easytensor/babysitter
      context: babysitter
      docker:
        dockerfile: Dockerfile
    - image: easytensor/query
      context: query
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/dev
profiles:
  - name: base
    deploy:
      kustomize:
        paths:
          - k8s/base
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/prod
