apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: easytensor
    service: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
