apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-http-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - app.easytensor.com
      secretName: app-easytensor-tls
    - hosts:
        - blog.easytensor.com
      secretName: blog-easytensor-tls
  rules:
    - host: app.easytensor.com
      http:
        paths:
          - path: /v1/.*
            backend:
              serviceName: backend-service
              servicePort: http
          - path: /query/
            backend:
              serviceName: query-service
              servicePort: http
          - path: /model-status/
            backend:
              serviceName: reporter-service
              servicePort: http
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: http
    - host: blog.easytensor.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: blog-service
  # tls:
  # - hosts:
  #   - argocd.easytensor.com
