# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

# list of Resource Config to be Applied
# resources:
# - deployment.yaml
images:
  - name: easytensor/tusd
    newName: gcr.io/easytensor-291022/tusd
# namespace to deploy all Resources to
namespace: prod

# labels added to all Resources
commonLabels:
  deployment_env: prod
