# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: prod

bases:
  - ../base

# list of Resource Config to be Applied
resources:
- deployment.yaml
- secrets/sealed-jwt-secret.yaml
- secrets/sealed-django-secret.yaml
- secrets/sealed-database-secret.yaml

patchesStrategicMerge:
- database-patch.yaml

patchesJson6902:
- target:
    group: ""
    version: v1
    kind: Service
    name: backend-service
    namespace: prod
  path: backend-service-patch.yaml


# labels added to all Resources
commonLabels:
  deployment_env: prod

configMapGenerator:
- name: frontend-properties
  envs:
  - frontend.properties
- name: service-routing
  behavior: merge
  envs:
  - service-routing.properties

generatorOptions:
  disableNameSuffixHash: true
