# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: prod

bases:
  - ../base

# list of Resource Config to be Applied
resources:
- deployment.yaml
- secrets/sealed-jwt-secret.yaml
- secrets/sealed-django-secret.yaml
- secrets/sealed-database-secret.yaml
- secrets/sealed-google-SA-secret.yaml

patchesStrategicMerge:
- database-patch.yaml

patchesJson6902:
- target:
    group: ""
    version: v1
    kind: Service
    name: backend-service
    namespace: prod
  path: backend-service-patch.yaml


images:
- name: easytensor/frontend
  newName: gcr.io/easytensor-291022/easytensor/frontend
  newTag: 1d9246d702b5b7e0e256a815f0d3ffb9d3285bc6
- name: easytensor/backend
  newName: gcr.io/easytensor-291022/easytensor/backend
  newTag: 1d9246d702b5b7e0e256a815f0d3ffb9d3285bc6
- name: easytensor/controller
  newName: gcr.io/easytensor-291022/easytensor/controller
  newTag: 1d9246d702b5b7e0e256a815f0d3ffb9d3285bc6
- name: easytensor/query
  newName: gcr.io/easytensor-291022/easytensor/query
  newTag: 1d9246d702b5b7e0e256a815f0d3ffb9d3285bc6


# labels added to all Resources
commonLabels:
  deployment_env: prod

configMapGenerator:
- name: frontend-properties
  envs:
  - frontend.properties
- name: service-routing
  behavior: merge
  envs:
  - service-routing.properties

generatorOptions:
  disableNameSuffixHash: true
