# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

# list of Resource Config to be Applied
resources:
- deployment.yaml

patches:
- path: database-patch.yaml
  target:
    kind: Deployment
    labelSelector: "app=easytensor,service=backend"
- path: backend-service-patch.yaml
  target:
    kind: Service
    labelSelector: "app=easytensor,service=backend"

# namespace to deploy all Resources to
namespace: prod

# labels added to all Resources
commonLabels:
  deployment_env: prod

configMapGenerator:
- name: frontend-properties
  env: frontend.properties
- name: backend-properties
  behavior: merge
  env: backend.properties.secret

generatorOptions:
  disableNameSuffixHash: true
