# Generated by Django 3.1.3 on 2020-11-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_queryaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='framework',
            field=models.CharField(choices=[('TF', 'Tensorflow'), ('PT', 'PyTorch')], default='TF', max_length=2),
        ),
    ]
