# Generated by Django 3.1.7 on 2021-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_make_tags_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='framework',
            field=models.CharField(choices=[('TF', 'Tensorflow'), ('PT', 'PyTorch'), ('TR', 'Transformers')], default='TF', max_length=2),
        ),
    ]
