FROM golang:latest

RUN apt update && apt install -y vim && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
ENV GOBIN=/app/
COPY . .
RUN go get -u github.com/cosmtrek/air
RUN go mod download
RUN go build

CMD ./air
