apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-tf-serve
  labels:
    app: easytensor
    service: tf-serve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: easytensor
      service: tf-serve
  template:
    metadata:
      labels:
        app: easytensor
        service: tf-serve
    spec:
      containers:
      - name: tf-serve
        image: tensorflow/serving
        ports:
        - containerPort: 8500
        - containerPort: 8501
        imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-upload
  labels:
    app: easytensor
    service: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytensor
  template:
    metadata:
      labels:
        app: easytensor
        service: upload
    spec:
      containers:
      - name: upload
        image: easytensor/tusd
        ports:
        - containerPort: 1080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector: 
    app: easytensor
    service: upload
  ports:
    - protocol: TCP
      port: 1080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-frontend
  labels:
    app: easytensor
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytensor
  template:
    metadata:
      labels:
        app: easytensor
        service: frontend
    spec:
      containers:
      - name: frontend
        image: easytensor/frontend
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: frontend-properties

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector: 
    app: easytensor
    service: frontend
  ports:
    - protocol: TCP
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-backend
  labels:
    app: easytensor
    service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytensor
  template:
    metadata:
      labels:
        app: easytensor
        service: backend
    spec:
      containers:
      - name: backend
        image: easytensor/backend
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector: 
    app: easytensor
    service: backend
  ports:
    - protocol: TCP
      port: 8000
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: et-controller
  labels:
    app: easytensor
    service: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytensor
  template:
    metadata:
      labels:
        app: easytensor
        service: controller
    spec:
      containers:
      - name: controller
        image: easytensor/controller
        imagePullPolicy: IfNotPresent
