# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- deployment.yaml

configMapGenerator:
- name: backend-properties
  env: backend.properties

secretGenerator:
- name: google-service-account
  files: 
    - google-SA-secret.txt
  type: Opaque
- name: jwt-secret
  files: 
    - jwt-secret
  type: Opaque
- name: django-secret
  files: 
    - django-secret
  type: Opaque

generatorOptions: 
  disableNameSuffixHash: true
