# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
- deployment.yaml

configMapGenerator:
- name: backend-properties
  envs:
  - backend.properties
- name: service-routing
  envs:
  - service-routing.properties
- name: controller-properties
  envs:
  - controller.properties
- name: mesh-account-cred
  envs:
  - mesh-account.properties
- name: reporter-properties
  envs:
  - reporter.properties


generatorOptions: 
  disableNameSuffixHash: true
